# Teaching Python

## Basics 

In [28]:
40 + 2 

42

See shortcuts in the short cut menu


In [29]:
#Importing package for computations
import numpy as np

In [30]:
## Getting the result of first computation
Out[1]
x= Out[1]
x

42

In [31]:
np.sin(90)

0.8939966636005579

In [32]:
#to check help
np.sin?

In [33]:
#to check source code 
np.any??

### Magic Commands


In [34]:
#to see all magic commands 
%magic

In [35]:
#Current working directory 
%pwd

'/Users/alice/Documents/Programming Projects'

In [37]:
%%time
for i in range(5):
    print(np.sin(5))

-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
CPU times: user 659 µs, sys: 318 µs, total: 977 µs
Wall time: 713 µs


In [38]:
%magic

In [39]:
#to see all files on the var log directory
!ls /var/log

Bluetooth                 fsck_apfs_error.log       uucp
CDIS.custom               fsck_hfs.log              weekly.out
CoreDuet                  install.log               wifi.log
DiagnosticMessages        monthly.out               wifi.log.0.bz2
apache2                   powermanagement           wifi.log.1.bz2
asl                       ppp                       wifi.log.10.bz2
com.apple.xpc.launchd     shutdown_monitor.log      wifi.log.2.bz2
corecaptured.log          system.log                wifi.log.3.bz2
cups                      system.log.0.gz           wifi.log.4.bz2
daily.out                 system.log.1.gz           wifi.log.5.bz2
displaypolicy             system.log.2.gz           wifi.log.6.bz2
displaypolicyd.stdout.log system.log.3.gz           wifi.log.7.bz2
emond                     system.log.4.gz           wifi.log.8.bz2
fsck_apfs.log             system.log.5.gz           wifi.log.9.bz2


In [40]:
dir_name = '/var/log'
!ls $dir_name

Bluetooth                 fsck_apfs_error.log       uucp
CDIS.custom               fsck_hfs.log              weekly.out
CoreDuet                  install.log               wifi.log
DiagnosticMessages        monthly.out               wifi.log.0.bz2
apache2                   powermanagement           wifi.log.1.bz2
asl                       ppp                       wifi.log.10.bz2
com.apple.xpc.launchd     shutdown_monitor.log      wifi.log.2.bz2
corecaptured.log          system.log                wifi.log.3.bz2
cups                      system.log.0.gz           wifi.log.4.bz2
daily.out                 system.log.1.gz           wifi.log.5.bz2
displaypolicy             system.log.2.gz           wifi.log.6.bz2
displaypolicyd.stdout.log system.log.3.gz           wifi.log.7.bz2
emond                     system.log.4.gz           wifi.log.8.bz2
fsck_apfs.log             system.log.5.gz           wifi.log.9.bz2


In [41]:
files = !ls /var/log
#REPL - read, eval, print and loop
print('We have {} files at {}'.format(len(files),dir_name))

We have 42 files at /var/log


How to make bullet points in markdown: 
* This 
* is 
* a 
* list 

HTML hyperlink: 
[Pandas](http://pandas.pydata.org) is awesome.

We can also add images via URL: 
![](https://cdn.pixabay.com/photo/2013/04/01/09/07/wink-98461_1280.png)

And, we can enter LaTex script: 

$e^x$ 
$$ \ln(e^x) = x $$

## NumPy Basics


* Building block of most scietific packages in Python 
* Provides fast arrays, math functions, linear algebra, randomization, and more
* Not the best option for speed and memoy consumption 

In [43]:
# power operation 4^2 
4 ** 2

16

In [44]:
np.int64(2) ** 1000

0

In [46]:
## Creating arrays 
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [47]:
len(arr)

3

In [48]:
arr[1]

2

In [49]:
type(arr[1])

numpy.int64

In [52]:
# array data type
arr.dtype

dtype('int64')

In [56]:
#specifying the data type of an array
arr32 = np.array( [1,2,3] , dtype = np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [57]:
arr * arr

array([1, 4, 9])

In [59]:
v1 = np.random.rand(10000)
v2 = np.random.rand(10000)

In [61]:
%time v1 * v2

CPU times: user 369 µs, sys: 260 µs, total: 629 µs
Wall time: 416 µs


array([0.70582575, 0.64015528, 0.38480272, ..., 0.36564099, 0.12410633,
       0.18540817])

In [65]:
#dot product
np.dot(arr,arr)

14

In [66]:
arr @ arr

14

In [69]:
# making matrix 
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
#faster way of making the same matrix above
v = np.arange(12)
v.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [80]:
mat = np.arange(12).reshape((4,3))

In [81]:
mat.shape


(4, 3)

In [83]:
mat2 = mat.reshape(3,4)
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
mat[1,2] = 17 

In [86]:
mat2

array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
#transpose 
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2, 17,  8, 11]])

In [91]:
#slicing
nums = [1,2,3,4,5]
nums[2:4]
#remember python index starts at 0

[3, 4]

In [92]:
v = np.arange(1,6)
v[2:4]

array([3, 4])

In [95]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
arr[0]

array([0, 1, 2, 3])

In [97]:
arr[1,1]

5

In [98]:
arr[:,1]

array([1, 5, 9])

In [99]:
arr[:,1].reshape((3,1))

array([[1],
       [5],
       [9]])

In [100]:
arr[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [101]:
#broadcasting
arr[1:,2:] = 7

In [102]:
arr

array([[0, 1, 2, 3],
       [4, 5, 7, 7],
       [8, 9, 7, 7]])

In [106]:
#boolean indexing 
arr = np.arange(3)
arr

array([0, 1, 2])

In [107]:
arr[np.array([True,False,True])]
arr >= 1

array([False,  True,  True])

In [108]:
arr[arr>=1]

array([1, 2])

In [111]:
arr = np.arange(10)

In [113]:
arr[(arr>2)&(arr<7)]

array([3, 4, 5, 6])

In [114]:
arr[(arr>2)|(arr>7)]

array([3, 4, 5, 6, 7, 8, 9])

In [116]:
#returns all values less than or equal to seven
arr[~(arr>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [118]:
mat = np.random.rand(5,5)
mat

array([[0.85480292, 0.18475073, 0.39836355, 0.74412676, 0.69526169],
       [0.73677853, 0.03205521, 0.3492551 , 0.30459129, 0.50325493],
       [0.17614231, 0.36083138, 0.90406519, 0.12025376, 0.97392983],
       [0.87841889, 0.5907909 , 0.33498825, 0.93502077, 0.43926261],
       [0.49084737, 0.43240751, 0.49900118, 0.13685013, 0.18301343]])

In [120]:
#finding all values that are more than 1/2 std devation from the mean
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()]

array([0.03205521, 0.97392983, 0.93502077])

In [122]:
#normalizing all these outliers to the mean
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()] = mat.mean()

In [124]:
arr = np.arange(3)
arr+4

array([4, 5, 6])

In [125]:
arr/7

array([0.        , 0.14285714, 0.28571429])

In [126]:
arr ** 2

array([0, 1, 4])

In [128]:
mat = np.arange(9).reshape((3,3))
vec = np.arange(3)

In [129]:
mat+vec

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [130]:
v1 = np.arange(3)
v2 = np.arange(3).reshape((3,1))

In [131]:
v2

array([[0],
       [1],
       [2]])

In [134]:
v2.shape

(3, 1)

In [135]:
v1 + v2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [138]:
#example of common matrix errors 
# np.arange (3) + np.arange(4)

dir command 
* to see what attributes and methods are in an object

In [139]:
v = np.arange(12).reshape((4,3))

In [140]:
dir(v)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [143]:
v.any()

True

In [144]:
v.all()

False

In [147]:
import this


In [149]:
if v.any():
    print('v is True')

v is True


In [150]:
v.prod()

0

In [151]:
v.sum(axis=1)

array([ 3, 12, 21, 30])

In [152]:
v.sum(axis=0)

array([18, 22, 26])

In [157]:
v1 = v.copy()

In [158]:
v1[0,0] = 1000

In [160]:
v1

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [161]:
data = v.dumps()
data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X`\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [163]:
v2 = np.loads(data)
v2

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: np.loads is deprecated, use pickle.loads instead
  """Entry point for launching an IPython kernel.


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [164]:
np.prod(v)

0

In [165]:
np.sin(np.pi/2)

1.0

In [167]:
v = np.arange(-3,3)
v

array([-3, -2, -1,  0,  1,  2])

In [168]:
np.sin(v)

array([-0.14112001, -0.90929743, -0.84147098,  0.        ,  0.84147098,
        0.90929743])

In [169]:
def noneg(n):
    if n <0: 
        return 0
    return n


In [170]:
noneg(7)

7

In [171]:
noneg(-3)

0

In [173]:
#example of error
#noneg(v)


In [174]:
# we fix this problem by the following:
@np.vectorize
def noneg(n):
    if n <0: 
        return 0
    return n

In [175]:
noneg = np.vectorize(noneg)

In [176]:
noneg(3)

array(3)

In [177]:
noneg(3).shape

()

In [178]:
noneg(v)

array([0, 0, 0, 0, 1, 2])

In [180]:
nv = np.array([-1,np.nan,1])
np.sin(nv)

array([-0.84147098,         nan,  0.84147098])

In [181]:
#another example of error
#noneg(nv)

In [182]:
np.nan>0


False

In [183]:
np.nan <0

False

In [184]:
np.nan == np.nan

False

In [187]:
@np.vectorize
def noneg(n):
    if not np.isnan(n) and n <0: 
        return n.__class__(0)
    return n

In [189]:
noneg(nv)
#now it works

array([ 0., nan,  1.])

In [190]:
#another way 
@np.vectorize
def isneg(n):
    return not np.isnan(n) and n < 0 

In [191]:
nv[isneg(nv)] = 0

In [192]:
nv

array([ 0., nan,  1.])

## Pandas

* Library for real-world data
* Adopted by Python scientific community as the main tool for working with data
* Many I/O tools
* Supports heterogeneous data (mixed types)
* Time series functionality
* Efficient with large amounts of data