# Teaching Python

## Basics 

In [28]:
40 + 2 

42

See shortcuts in the short cut menu


In [29]:
#Importing package for computations
import numpy as np

In [30]:
## Getting the result of first computation
Out[1]
x= Out[1]
x

42

In [31]:
np.sin(90)

0.8939966636005579

In [32]:
#to check help
np.sin?

In [33]:
#to check source code 
np.any??

### Magic Commands


In [34]:
#to see all magic commands 
%magic

In [35]:
#Current working directory 
%pwd

'/Users/alice/Documents/Programming Projects'

In [37]:
%%time
for i in range(5):
    print(np.sin(5))

-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
CPU times: user 659 µs, sys: 318 µs, total: 977 µs
Wall time: 713 µs


In [38]:
%magic

In [39]:
#to see all files on the var log directory
!ls /var/log

Bluetooth                 fsck_apfs_error.log       uucp
CDIS.custom               fsck_hfs.log              weekly.out
CoreDuet                  install.log               wifi.log
DiagnosticMessages        monthly.out               wifi.log.0.bz2
apache2                   powermanagement           wifi.log.1.bz2
asl                       ppp                       wifi.log.10.bz2
com.apple.xpc.launchd     shutdown_monitor.log      wifi.log.2.bz2
corecaptured.log          system.log                wifi.log.3.bz2
cups                      system.log.0.gz           wifi.log.4.bz2
daily.out                 system.log.1.gz           wifi.log.5.bz2
displaypolicy             system.log.2.gz           wifi.log.6.bz2
displaypolicyd.stdout.log system.log.3.gz           wifi.log.7.bz2
emond                     system.log.4.gz           wifi.log.8.bz2
fsck_apfs.log             system.log.5.gz           wifi.log.9.bz2


In [40]:
dir_name = '/var/log'
!ls $dir_name

Bluetooth                 fsck_apfs_error.log       uucp
CDIS.custom               fsck_hfs.log              weekly.out
CoreDuet                  install.log               wifi.log
DiagnosticMessages        monthly.out               wifi.log.0.bz2
apache2                   powermanagement           wifi.log.1.bz2
asl                       ppp                       wifi.log.10.bz2
com.apple.xpc.launchd     shutdown_monitor.log      wifi.log.2.bz2
corecaptured.log          system.log                wifi.log.3.bz2
cups                      system.log.0.gz           wifi.log.4.bz2
daily.out                 system.log.1.gz           wifi.log.5.bz2
displaypolicy             system.log.2.gz           wifi.log.6.bz2
displaypolicyd.stdout.log system.log.3.gz           wifi.log.7.bz2
emond                     system.log.4.gz           wifi.log.8.bz2
fsck_apfs.log             system.log.5.gz           wifi.log.9.bz2


In [41]:
files = !ls /var/log
#REPL - read, eval, print and loop
print('We have {} files at {}'.format(len(files),dir_name))

We have 42 files at /var/log


How to make bullet points in markdown: 
* This 
* is 
* a 
* list 

HTML hyperlink: 
[Pandas](http://pandas.pydata.org) is awesome.

We can also add images via URL: 
![](https://cdn.pixabay.com/photo/2013/04/01/09/07/wink-98461_1280.png)

And, we can enter LaTex script: 

$e^x$ 
$$ \ln(e^x) = x $$

## NumPy Basics


* Building block of most scietific packages in Python 
* Provides fast arrays, math functions, linear algebra, randomization, and more
* Not the best option for speed and memoy consumption 

In [43]:
# power operation 4^2 
4 ** 2

16

In [44]:
np.int64(2) ** 1000

0

In [46]:
## Creating arrays 
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [47]:
len(arr)

3

In [48]:
arr[1]

2

In [49]:
type(arr[1])

numpy.int64

In [52]:
# array data type
arr.dtype

dtype('int64')

In [56]:
#specifying the data type of an array
arr32 = np.array( [1,2,3] , dtype = np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [57]:
arr * arr

array([1, 4, 9])

In [59]:
v1 = np.random.rand(10000)
v2 = np.random.rand(10000)

In [61]:
%time v1 * v2

CPU times: user 369 µs, sys: 260 µs, total: 629 µs
Wall time: 416 µs


array([0.70582575, 0.64015528, 0.38480272, ..., 0.36564099, 0.12410633,
       0.18540817])

In [65]:
#dot product
np.dot(arr,arr)

14

In [66]:
arr @ arr

14

In [69]:
# making matrix 
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
#faster way of making the same matrix above
v = np.arange(12)
v.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [80]:
mat = np.arange(12).reshape((4,3))

In [81]:
mat.shape


(4, 3)

In [83]:
mat2 = mat.reshape(3,4)
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
mat[1,2] = 17 

In [86]:
mat2

array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
#transpose 
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2, 17,  8, 11]])

In [91]:
#slicing
nums = [1,2,3,4,5]
nums[2:4]
#remember python index starts at 0

[3, 4]

In [92]:
v = np.arange(1,6)
v[2:4]

array([3, 4])

In [95]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
arr[0]

array([0, 1, 2, 3])

In [97]:
arr[1,1]

5

In [98]:
arr[:,1]

array([1, 5, 9])

In [99]:
arr[:,1].reshape((3,1))

array([[1],
       [5],
       [9]])

In [100]:
arr[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [101]:
#broadcasting
arr[1:,2:] = 7

In [102]:
arr

array([[0, 1, 2, 3],
       [4, 5, 7, 7],
       [8, 9, 7, 7]])

In [106]:
#boolean indexing 
arr = np.arange(3)
arr

array([0, 1, 2])

In [107]:
arr[np.array([True,False,True])]
arr >= 1

array([False,  True,  True])

In [108]:
arr[arr>=1]

array([1, 2])

In [111]:
arr = np.arange(10)

In [113]:
arr[(arr>2)&(arr<7)]

array([3, 4, 5, 6])

In [114]:
arr[(arr>2)|(arr>7)]

array([3, 4, 5, 6, 7, 8, 9])

In [116]:
#returns all values less than or equal to seven
arr[~(arr>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [118]:
mat = np.random.rand(5,5)
mat

array([[0.85480292, 0.18475073, 0.39836355, 0.74412676, 0.69526169],
       [0.73677853, 0.03205521, 0.3492551 , 0.30459129, 0.50325493],
       [0.17614231, 0.36083138, 0.90406519, 0.12025376, 0.97392983],
       [0.87841889, 0.5907909 , 0.33498825, 0.93502077, 0.43926261],
       [0.49084737, 0.43240751, 0.49900118, 0.13685013, 0.18301343]])

In [120]:
#finding all values that are more than 1/2 std devation from the mean
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()]

array([0.03205521, 0.97392983, 0.93502077])

In [122]:
#normalizing all these outliers to the mean
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()] = mat.mean()