# Teaching Python

## Basics 

In [28]:
40 + 2 

42

See shortcuts in the short cut menu


In [29]:
#Importing package for computations
import numpy as np

In [30]:
## Getting the result of first computation
Out[1]
x= Out[1]
x

42

In [31]:
np.sin(90)

0.8939966636005579

In [32]:
#to check help
np.sin?

In [33]:
#to check source code 
np.any??

### Magic Commands


In [34]:
#to see all magic commands 
%magic

In [35]:
#Current working directory 
%pwd

'/Users/alice/Documents/Programming Projects'

In [37]:
%%time
for i in range(5):
    print(np.sin(5))

-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
-0.9589242746631385
CPU times: user 659 µs, sys: 318 µs, total: 977 µs
Wall time: 713 µs


In [38]:
%magic

In [39]:
#to see all files on the var log directory
!ls /var/log

Bluetooth                 fsck_apfs_error.log       uucp
CDIS.custom               fsck_hfs.log              weekly.out
CoreDuet                  install.log               wifi.log
DiagnosticMessages        monthly.out               wifi.log.0.bz2
apache2                   powermanagement           wifi.log.1.bz2
asl                       ppp                       wifi.log.10.bz2
com.apple.xpc.launchd     shutdown_monitor.log      wifi.log.2.bz2
corecaptured.log          system.log                wifi.log.3.bz2
cups                      system.log.0.gz           wifi.log.4.bz2
daily.out                 system.log.1.gz           wifi.log.5.bz2
displaypolicy             system.log.2.gz           wifi.log.6.bz2
displaypolicyd.stdout.log system.log.3.gz           wifi.log.7.bz2
emond                     system.log.4.gz           wifi.log.8.bz2
fsck_apfs.log             system.log.5.gz           wifi.log.9.bz2


In [40]:
dir_name = '/var/log'
!ls $dir_name

Bluetooth                 fsck_apfs_error.log       uucp
CDIS.custom               fsck_hfs.log              weekly.out
CoreDuet                  install.log               wifi.log
DiagnosticMessages        monthly.out               wifi.log.0.bz2
apache2                   powermanagement           wifi.log.1.bz2
asl                       ppp                       wifi.log.10.bz2
com.apple.xpc.launchd     shutdown_monitor.log      wifi.log.2.bz2
corecaptured.log          system.log                wifi.log.3.bz2
cups                      system.log.0.gz           wifi.log.4.bz2
daily.out                 system.log.1.gz           wifi.log.5.bz2
displaypolicy             system.log.2.gz           wifi.log.6.bz2
displaypolicyd.stdout.log system.log.3.gz           wifi.log.7.bz2
emond                     system.log.4.gz           wifi.log.8.bz2
fsck_apfs.log             system.log.5.gz           wifi.log.9.bz2


In [41]:
files = !ls /var/log
#REPL - read, eval, print and loop
print('We have {} files at {}'.format(len(files),dir_name))

We have 42 files at /var/log


How to make bullet points in markdown: 
* This 
* is 
* a 
* list 

HTML hyperlink: 
[Pandas](http://pandas.pydata.org) is awesome.

We can also add images via URL: 
![](https://cdn.pixabay.com/photo/2013/04/01/09/07/wink-98461_1280.png)

And, we can enter LaTex script: 

$e^x$ 
$$ \ln(e^x) = x $$

## NumPy Basics


* Building block of most scietific packages in Python 
* Provides fast arrays, math functions, linear algebra, randomization, and more
* Not the best option for speed and memoy consumption 

In [43]:
# power operation 4^2 
4 ** 2

16

In [44]:
np.int64(2) ** 1000

0

In [46]:
## Creating arrays 
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [47]:
len(arr)

3

In [48]:
arr[1]

2

In [49]:
type(arr[1])

numpy.int64

In [52]:
# array data type
arr.dtype

dtype('int64')

In [56]:
#specifying the data type of an array
arr32 = np.array( [1,2,3] , dtype = np.int32)
arr32

array([1, 2, 3], dtype=int32)

In [57]:
arr * arr

array([1, 4, 9])

In [59]:
v1 = np.random.rand(10000)
v2 = np.random.rand(10000)

In [61]:
%time v1 * v2

CPU times: user 369 µs, sys: 260 µs, total: 629 µs
Wall time: 416 µs


array([0.70582575, 0.64015528, 0.38480272, ..., 0.36564099, 0.12410633,
       0.18540817])

In [65]:
#dot product
np.dot(arr,arr)

14

In [66]:
arr @ arr

14

In [69]:
# making matrix 
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
#faster way of making the same matrix above
v = np.arange(12)
v.reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [80]:
mat = np.arange(12).reshape((4,3))

In [81]:
mat.shape


(4, 3)

In [83]:
mat2 = mat.reshape(3,4)
mat2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
mat[1,2] = 17 

In [86]:
mat2

array([[ 0,  1,  2,  3],
       [ 4, 17,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
#transpose 
mat.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2, 17,  8, 11]])

In [91]:
#slicing
nums = [1,2,3,4,5]
nums[2:4]
#remember python index starts at 0

[3, 4]

In [92]:
v = np.arange(1,6)
v[2:4]

array([3, 4])

In [95]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [96]:
arr[0]

array([0, 1, 2, 3])

In [97]:
arr[1,1]

5

In [98]:
arr[:,1]

array([1, 5, 9])

In [99]:
arr[:,1].reshape((3,1))

array([[1],
       [5],
       [9]])

In [100]:
arr[1:,2:]

array([[ 6,  7],
       [10, 11]])

In [101]:
#broadcasting
arr[1:,2:] = 7

In [102]:
arr

array([[0, 1, 2, 3],
       [4, 5, 7, 7],
       [8, 9, 7, 7]])

In [106]:
#boolean indexing 
arr = np.arange(3)
arr

array([0, 1, 2])

In [107]:
arr[np.array([True,False,True])]
arr >= 1

array([False,  True,  True])

In [108]:
arr[arr>=1]

array([1, 2])

In [111]:
arr = np.arange(10)

In [113]:
arr[(arr>2)&(arr<7)]

array([3, 4, 5, 6])

In [114]:
arr[(arr>2)|(arr>7)]

array([3, 4, 5, 6, 7, 8, 9])

In [116]:
#returns all values less than or equal to seven
arr[~(arr>7)]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [118]:
mat = np.random.rand(5,5)
mat

array([[0.85480292, 0.18475073, 0.39836355, 0.74412676, 0.69526169],
       [0.73677853, 0.03205521, 0.3492551 , 0.30459129, 0.50325493],
       [0.17614231, 0.36083138, 0.90406519, 0.12025376, 0.97392983],
       [0.87841889, 0.5907909 , 0.33498825, 0.93502077, 0.43926261],
       [0.49084737, 0.43240751, 0.49900118, 0.13685013, 0.18301343]])

In [120]:
#finding all values that are more than 1/2 std devation from the mean
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()]

array([0.03205521, 0.97392983, 0.93502077])

In [122]:
#normalizing all these outliers to the mean
mat[np.abs(mat-mat.mean()) > 1.5*mat.std()] = mat.mean()

In [124]:
arr = np.arange(3)
arr+4

array([4, 5, 6])

In [125]:
arr/7

array([0.        , 0.14285714, 0.28571429])

In [126]:
arr ** 2

array([0, 1, 4])

In [128]:
mat = np.arange(9).reshape((3,3))
vec = np.arange(3)

In [129]:
mat+vec

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [130]:
v1 = np.arange(3)
v2 = np.arange(3).reshape((3,1))

In [131]:
v2

array([[0],
       [1],
       [2]])

In [134]:
v2.shape

(3, 1)

In [135]:
v1 + v2

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [138]:
#example of common matrix errors 
# np.arange (3) + np.arange(4)

dir command 
* to see what attributes and methods are in an object

In [139]:
v = np.arange(12).reshape((4,3))

In [140]:
dir(v)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [143]:
v.any()

True

In [144]:
v.all()

False

In [147]:
import this


In [149]:
if v.any():
    print('v is True')

v is True


In [150]:
v.prod()

0

In [151]:
v.sum(axis=1)

array([ 3, 12, 21, 30])

In [152]:
v.sum(axis=0)

array([18, 22, 26])

In [157]:
v1 = v.copy()

In [158]:
v1[0,0] = 1000

In [160]:
v1

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [161]:
data = v.dumps()
data

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x03\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i8q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X`\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\t\x00\x00\x00\x00\x00\x00\x00\n\x00\x00\x00\x00\x00\x00\x00\x0b\x00\x00\x00\x00\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [163]:
v2 = np.loads(data)
v2

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: np.loads is deprecated, use pickle.loads instead
  """Entry point for launching an IPython kernel.


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [164]:
np.prod(v)

0

In [165]:
np.sin(np.pi/2)

1.0

In [167]:
v = np.arange(-3,3)
v

array([-3, -2, -1,  0,  1,  2])

In [168]:
np.sin(v)

array([-0.14112001, -0.90929743, -0.84147098,  0.        ,  0.84147098,
        0.90929743])

In [169]:
def noneg(n):
    if n <0: 
        return 0
    return n


In [170]:
noneg(7)

7

In [171]:
noneg(-3)

0

In [173]:
#example of error
#noneg(v)


In [174]:
# we fix this problem by the following:
@np.vectorize
def noneg(n):
    if n <0: 
        return 0
    return n

In [175]:
noneg = np.vectorize(noneg)

In [176]:
noneg(3)

array(3)

In [177]:
noneg(3).shape

()

In [178]:
noneg(v)

array([0, 0, 0, 0, 1, 2])

In [180]:
nv = np.array([-1,np.nan,1])
np.sin(nv)

array([-0.84147098,         nan,  0.84147098])

In [181]:
#another example of error
#noneg(nv)

In [182]:
np.nan>0


False

In [183]:
np.nan <0

False

In [184]:
np.nan == np.nan

False

In [187]:
@np.vectorize
def noneg(n):
    if not np.isnan(n) and n <0: 
        return n.__class__(0)
    return n

In [189]:
noneg(nv)
#now it works

array([ 0., nan,  1.])

In [190]:
#another way 
@np.vectorize
def isneg(n):
    return not np.isnan(n) and n < 0 

In [191]:
nv[isneg(nv)] = 0

In [192]:
nv

array([ 0., nan,  1.])

## Pandas

* Library for real-world data
* Adopted by Python scientific community as the main tool for working with data
* Many I/O tools
* Supports heterogeneous data (mixed types)
* Time series functionality
* Efficient with large amounts of data

In [194]:
#edit this code based on where you've saved the track.csv on your computer
from os import path
fname = path.expanduser('/Users/alice/Desktop/track.csv')

In [195]:
!ls -lh "$fname"

-rwxrwxrwx@ 1 alice  staff    43K Apr  7  2017 /Users/alice/Desktop/track.csv


In [196]:
path.getsize(fname)

43844

In [197]:
path.getsize(fname) / (1<<10)

42.81640625

In [200]:
with open(fname) as fp:
    for lnum, line in enumerate(fp):
        if lnum > 10: 
            break
        print(line[:-1])

time,lat,lng,height
2015-08-20 03:48:07.235,35.015021,32.519585,136.1999969482422
2015-08-20 03:48:24.734,35.014954,32.519606,126.5999984741211
2015-08-20 03:48:25.660,35.014871,32.519612,123.0
2015-08-20 03:48:26.819,35.014824,32.519654,120.5
2015-08-20 03:48:27.828,35.014776,32.519689,118.9000015258789
2015-08-20 03:48:29.720,35.014704,32.519691,119.9000015258789
2015-08-20 03:48:30.669,35.014657,32.519734,120.9000015258789
2015-08-20 03:48:33.793,35.014563,32.519719,121.69999694824219
2015-08-20 03:48:34.869,35.014549,32.519694,121.19999694824219
2015-08-20 03:48:37.708,35.014515,32.519625,121.69999694824219


In [202]:
!wc -l "$fname"

     741 /Users/alice/Desktop/track.csv


In [203]:
with open(fname) as fp: 
    print(sum(1 for line in fp))

741


In [204]:
import pandas as pd

In [205]:
df = pd.read_csv(fname)

In [206]:
len(df)

740

In [207]:
df.columns

Index(['time', 'lat', 'lng', 'height'], dtype='object')

In [208]:
df.info

<bound method DataFrame.info of                         time        lat        lng      height
0    2015-08-20 03:48:07.235  35.015021  32.519585  136.199997
1    2015-08-20 03:48:24.734  35.014954  32.519606  126.599998
2    2015-08-20 03:48:25.660  35.014871  32.519612  123.000000
3    2015-08-20 03:48:26.819  35.014824  32.519654  120.500000
4    2015-08-20 03:48:27.828  35.014776  32.519689  118.900002
5    2015-08-20 03:48:29.720  35.014704  32.519691  119.900002
6    2015-08-20 03:48:30.669  35.014657  32.519734  120.900002
7    2015-08-20 03:48:33.793  35.014563  32.519719  121.699997
8    2015-08-20 03:48:34.869  35.014549  32.519694  121.199997
9    2015-08-20 03:48:37.708  35.014515  32.519625  121.699997
10   2015-08-20 03:48:38.839  35.014505  32.519599  121.800003
11   2015-08-20 03:48:41.980  35.014481  32.519514  122.599998
12   2015-08-20 03:48:42.725  35.014472  32.519486  123.000000
13   2015-08-20 03:48:45.896  35.014439  32.519405  122.699997
14   2015-08-20 03:48:4

In [209]:
df.head()

time        lat        lng      height
0  2015-08-20 03:48:07.235  35.015021  32.519585  136.199997
1  2015-08-20 03:48:24.734  35.014954  32.519606  126.599998
2  2015-08-20 03:48:25.660  35.014871  32.519612  123.000000
3  2015-08-20 03:48:26.819  35.014824  32.519654  120.500000
4  2015-08-20 03:48:27.828  35.014776  32.519689  118.900002

In [210]:
df.dtypes

time       object
lat       float64
lng       float64
height    float64
dtype: object

In [211]:
df = pd.read_csv(fname, parse_dates=['time'])

In [212]:
df.dtypes

time      datetime64[ns]
lat              float64
lng              float64
height           float64
dtype: object

In [213]:
df['lat']

0      35.015021
1      35.014954
2      35.014871
3      35.014824
4      35.014776
5      35.014704
6      35.014657
7      35.014563
8      35.014549
9      35.014515
10     35.014505
11     35.014481
12     35.014472
13     35.014439
14     35.014432
15     35.014414
16     35.014400
17     35.014372
18     35.014365
19     35.014337
20     35.014331
21     35.014303
22     35.014306
23     35.014340
24     35.013531
25     35.013606
26     35.013630
27     35.013705
28     35.013730
29     35.013809
         ...    
710    35.015705
711    35.015640
712    35.015617
713    35.015551
714    35.015533
715    35.015468
716    35.015444
717    35.015369
718    35.015343
719    35.015264
720    35.015238
721    35.015157
722    35.015129
723    35.015048
724    35.015023
725    35.014943
726    35.014916
727    35.014835
728    35.014810
729    35.014737
730    35.014709
731    35.014617
732    35.014584
733    35.014518
734    35.014484
735    35.014387
736    35.014355
737    35.0142

In [214]:
df.lat

0      35.015021
1      35.014954
2      35.014871
3      35.014824
4      35.014776
5      35.014704
6      35.014657
7      35.014563
8      35.014549
9      35.014515
10     35.014505
11     35.014481
12     35.014472
13     35.014439
14     35.014432
15     35.014414
16     35.014400
17     35.014372
18     35.014365
19     35.014337
20     35.014331
21     35.014303
22     35.014306
23     35.014340
24     35.013531
25     35.013606
26     35.013630
27     35.013705
28     35.013730
29     35.013809
         ...    
710    35.015705
711    35.015640
712    35.015617
713    35.015551
714    35.015533
715    35.015468
716    35.015444
717    35.015369
718    35.015343
719    35.015264
720    35.015238
721    35.015157
722    35.015129
723    35.015048
724    35.015023
725    35.014943
726    35.014916
727    35.014835
728    35.014810
729    35.014737
730    35.014709
731    35.014617
732    35.014584
733    35.014518
734    35.014484
735    35.014387
736    35.014355
737    35.0142

In [215]:
df[['lat', 'lng']]

lat        lng
0    35.015021  32.519585
1    35.014954  32.519606
2    35.014871  32.519612
3    35.014824  32.519654
4    35.014776  32.519689
5    35.014704  32.519691
6    35.014657  32.519734
7    35.014563  32.519719
8    35.014549  32.519694
9    35.014515  32.519625
10   35.014505  32.519599
11   35.014481  32.519514
12   35.014472  32.519486
13   35.014439  32.519405
14   35.014432  32.519379
15   35.014414  32.519309
16   35.014400  32.519287
17   35.014372  32.519211
18   35.014365  32.519187
19   35.014337  32.519106
20   35.014331  32.519084
21   35.014303  32.519009
22   35.014306  32.518989
23   35.014340  32.518916
24   35.013531  32.517636
25   35.013606  32.517589
26   35.013630  32.517574
27   35.013705  32.517529
28   35.013730  32.517512
29   35.013809  32.517459
..         ...        ...
710  35.015705  32.516157
711  35.015640  32.516211
712  35.015617  32.516225
713  35.015551  32.516278
714  35.015533  32.516301
715  35.015468  32.516361
716  35.015444  32.516380
717  35.015369  32.516442
718  35.015343  32.516462
719  35.015264  32.516517
720  35.015238  32.516537
721  35.015157  32.516592
722  35.015129  32.516610
723  35.015048  32.516665
724  35.015023  32.516683
725  35.014943  32.516736
726  35.014916  32.516754
727  35.014835  32.516800
728  35.014810  32.516818
729  35.014737  32.516873
730  35.014709  32.516889
731  35.014617  32.516933
732  35.014584  32.516945
733  35.014518  32.516971
734  35.014484  32.516984
735  35.014387  32.517020
736  35.014355  32.517035
737  35.014279  32.517087
738  35.014264  32.517098
739  35.014212  32.517142

[740 rows x 2 columns]

In [216]:
df['lat'][0]

35.015021000000004

In [217]:
df.loc[0]

time      2015-08-20 03:48:07.235000
lat                           35.015
lng                          32.5196
height                         136.2
Name: 0, dtype: object

In [218]:
df.loc[2:7]

time        lat        lng      height
2 2015-08-20 03:48:25.660  35.014871  32.519612  123.000000
3 2015-08-20 03:48:26.819  35.014824  32.519654  120.500000
4 2015-08-20 03:48:27.828  35.014776  32.519689  118.900002
5 2015-08-20 03:48:29.720  35.014704  32.519691  119.900002
6 2015-08-20 03:48:30.669  35.014657  32.519734  120.900002
7 2015-08-20 03:48:33.793  35.014563  32.519719  121.699997

In [219]:
df[['lat', 'lng']][2:7]

lat        lng
2  35.014871  32.519612
3  35.014824  32.519654
4  35.014776  32.519689
5  35.014704  32.519691
6  35.014657  32.519734

In [220]:
df.index

RangeIndex(start=0, stop=740, step=1)

In [221]:
df1 = pd.DataFrame(np.arange(10).reshape((5,2)), columns=['x', 'y'], index=['a', 'b', 'c', 'd', 'e'])
df1

x  y
a  0  1
b  2  3
c  4  5
d  6  7
e  8  9

In [222]:
df1.loc['a']

x    0
y    1
Name: a, dtype: int64

In [223]:
df1.loc['b': 'd']

x  y
b  2  3
c  4  5
d  6  7

In [224]:
df.index

RangeIndex(start=0, stop=740, step=1)

In [225]:
df.index = df['time']
df.index

DatetimeIndex(['2015-08-20 03:48:07.235000', '2015-08-20 03:48:24.734000',
               '2015-08-20 03:48:25.660000', '2015-08-20 03:48:26.819000',
               '2015-08-20 03:48:27.828000', '2015-08-20 03:48:29.720000',
               '2015-08-20 03:48:30.669000', '2015-08-20 03:48:33.793000',
               '2015-08-20 03:48:34.869000', '2015-08-20 03:48:37.708000',
               ...
               '2015-08-20 04:20:18.844000', '2015-08-20 04:20:21.996000',
               '2015-08-20 04:20:22.897000', '2015-08-20 04:20:24.905000',
               '2015-08-20 04:20:25.835000', '2015-08-20 04:20:28.982000',
               '2015-08-20 04:20:29.923000', '2015-08-20 04:20:32.863000',
               '2015-08-20 04:20:33.994000', '2015-08-20 04:20:42.329000'],
              dtype='datetime64[ns]', name='time', length=740, freq=None)

In [226]:
df.loc['2015-08-20 04:18:54']

time        lat        lng  \
time                                                                    
2015-08-20 04:18:54.007 2015-08-20 04:18:54.007  35.015942  32.515209   
2015-08-20 04:18:54.893 2015-08-20 04:18:54.893  35.015937  32.515240   

                             height  
time                                 
2015-08-20 04:18:54.007  117.099998  
2015-08-20 04:18:54.893  117.500000

In [227]:
df.loc['2015-08-20 03:48']

time        lat        lng  \
time                                                                    
2015-08-20 03:48:07.235 2015-08-20 03:48:07.235  35.015021  32.519585   
2015-08-20 03:48:24.734 2015-08-20 03:48:24.734  35.014954  32.519606   
2015-08-20 03:48:25.660 2015-08-20 03:48:25.660  35.014871  32.519612   
2015-08-20 03:48:26.819 2015-08-20 03:48:26.819  35.014824  32.519654   
2015-08-20 03:48:27.828 2015-08-20 03:48:27.828  35.014776  32.519689   
2015-08-20 03:48:29.720 2015-08-20 03:48:29.720  35.014704  32.519691   
2015-08-20 03:48:30.669 2015-08-20 03:48:30.669  35.014657  32.519734   
2015-08-20 03:48:33.793 2015-08-20 03:48:33.793  35.014563  32.519719   
2015-08-20 03:48:34.869 2015-08-20 03:48:34.869  35.014549  32.519694   
2015-08-20 03:48:37.708 2015-08-20 03:48:37.708  35.014515  32.519625   
2015-08-20 03:48:38.839 2015-08-20 03:48:38.839  35.014505  32.519599   
2015-08-20 03:48:41.980 2015-08-20 03:48:41.980  35.014481  32.519514   
2015-08-20 03:48:42.725 2015-08-20 03:48:42.725  35.014472  32.519486   
2015-08-20 03:48:45.896 2015-08-20 03:48:45.896  35.014439  32.519405   
2015-08-20 03:48:46.662 2015-08-20 03:48:46.662  35.014432  32.519379   
2015-08-20 03:48:49.829 2015-08-20 03:48:49.829  35.014414  32.519309   
2015-08-20 03:48:50.665 2015-08-20 03:48:50.665  35.014400  32.519287   
2015-08-20 03:48:53.692 2015-08-20 03:48:53.692  35.014372  32.519211   
2015-08-20 03:48:54.662 2015-08-20 03:48:54.662  35.014365  32.519187   
2015-08-20 03:48:58.869 2015-08-20 03:48:58.869  35.014337  32.519106   
2015-08-20 03:48:59.663 2015-08-20 03:48:59.663  35.014331  32.519084   

                             height  
time                                 
2015-08-20 03:48:07.235  136.199997  
2015-08-20 03:48:24.734  126.599998  
2015-08-20 03:48:25.660  123.000000  
2015-08-20 03:48:26.819  120.500000  
2015-08-20 03:48:27.828  118.900002  
2015-08-20 03:48:29.720  119.900002  
2015-08-20 03:48:30.669  120.900002  
2015-08-20 03:48:33.793  121.699997  
2015-08-20 03:48:34.869  121.199997  
2015-08-20 03:48:37.708  121.699997  
2015-08-20 03:48:38.839  121.800003  
2015-08-20 03:48:41.980  122.599998  
2015-08-20 03:48:42.725  123.000000  
2015-08-20 03:48:45.896  122.699997  
2015-08-20 03:48:46.662  122.699997  
2015-08-20 03:48:49.829  122.699997  
2015-08-20 03:48:50.665  123.300003  
2015-08-20 03:48:53.692  122.300003  
2015-08-20 03:48:54.662  122.599998  
2015-08-20 03:48:58.869  122.000000  
2015-08-20 03:48:59.663  121.800003

In [228]:
import pytz

In [229]:
ts = df.index[0]

In [230]:
ts.tz_localize(pytz.UTC)

Timestamp('2015-08-20 03:48:07.235000+0000', tz='UTC')

In [231]:
ts.tz_localize(pytz.UTC).tz_convert(pytz.timezone('Asia/Jerusalem'))

Timestamp('2015-08-20 06:48:07.235000+0300', tz='Asia/Jerusalem')

In [232]:
df.index = df.index.tz_localize(pytz.UTC).tz_convert(pytz.timezone('Asia/Jerusalem'))
df.index[:10]

DatetimeIndex(['2015-08-20 06:48:07.235000+03:00',
               '2015-08-20 06:48:24.734000+03:00',
               '2015-08-20 06:48:25.660000+03:00',
               '2015-08-20 06:48:26.819000+03:00',
               '2015-08-20 06:48:27.828000+03:00',
               '2015-08-20 06:48:29.720000+03:00',
               '2015-08-20 06:48:30.669000+03:00',
               '2015-08-20 06:48:33.793000+03:00',
               '2015-08-20 06:48:34.869000+03:00',
               '2015-08-20 06:48:37.708000+03:00'],
              dtype='datetime64[ns, Asia/Jerusalem]', name='time', freq=None)

In [233]:
%pwd

'/Users/alice/Documents/Programming Projects'

In [237]:
#make sure the geo.py file is in the same folder as this notebook
import geo

In [238]:
import sys
sys.path

['/Users/alice/Documents/Programming Projects',
 '/anaconda3/lib/python37.zip',
 '/anaconda3/lib/python3.7',
 '/anaconda3/lib/python3.7/lib-dynload',
 '',
 '/anaconda3/lib/python3.7/site-packages',
 '/anaconda3/lib/python3.7/site-packages/aeosa',
 '/anaconda3/lib/python3.7/site-packages/IPython/extensions',
 '/Users/alice/.ipython']

In [239]:
??geo

In [240]:
from geo import circle_dist

In [241]:
lat1, lng1 = df.iloc[0].lat, df.iloc[0].lng
lat2, lng2 = df.iloc[1].lat, df.iloc[1].lng

In [242]:
circle_dist(lat1, lng1, lat2, lng2)

0.007695103586769196

In [243]:
s = pd.Series(np.arange(5))

In [244]:
s

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [245]:
s.shift()

0    NaN
1    0.0
2    1.0
3    2.0
4    3.0
dtype: float64

In [246]:
s.shift(-1)

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
dtype: float64

In [247]:
dist = circle_dist(df['lat'], df['lng'], df['lat'].shift(), df['lng'].shift())

In [248]:
dist[:10]

time
2015-08-20 06:48:07.235000+03:00         NaN
2015-08-20 06:48:24.734000+03:00    0.007695
2015-08-20 06:48:25.660000+03:00    0.009248
2015-08-20 06:48:26.819000+03:00    0.006479
2015-08-20 06:48:27.828000+03:00    0.006219
2015-08-20 06:48:29.720000+03:00    0.008010
2015-08-20 06:48:30.669000+03:00    0.006533
2015-08-20 06:48:33.793000+03:00    0.010545
2015-08-20 06:48:34.869000+03:00    0.002759
2015-08-20 06:48:37.708000+03:00    0.007336
dtype: float64

In [249]:
dist.sum()

4.6881365592010695

In [250]:
dt = df['time'] - df['time'].shift()

In [251]:
dt[:10]

time
2015-08-20 06:48:07.235000+03:00               NaT
2015-08-20 06:48:24.734000+03:00   00:00:17.499000
2015-08-20 06:48:25.660000+03:00   00:00:00.926000
2015-08-20 06:48:26.819000+03:00   00:00:01.159000
2015-08-20 06:48:27.828000+03:00   00:00:01.009000
2015-08-20 06:48:29.720000+03:00   00:00:01.892000
2015-08-20 06:48:30.669000+03:00   00:00:00.949000
2015-08-20 06:48:33.793000+03:00   00:00:03.124000
2015-08-20 06:48:34.869000+03:00   00:00:01.076000
2015-08-20 06:48:37.708000+03:00   00:00:02.839000
Name: time, dtype: timedelta64[ns]

In [252]:
dt.sum()

Timedelta('0 days 00:32:35.094000')

In [253]:
dt[1].total_seconds()

17.499

In [254]:
dt[1] / np.timedelta64(1, 'h')

0.004860833333333333

In [255]:
dt[1].total_seconds()/3600

0.004860833333333333

In [256]:
speed = dist / (dt / np.timedelta64(1, 'h'))

In [257]:
speed[:10]

time
2015-08-20 06:48:07.235000+03:00          NaN
2015-08-20 06:48:24.734000+03:00     1.583083
2015-08-20 06:48:25.660000+03:00    35.954340
2015-08-20 06:48:26.819000+03:00    20.123165
2015-08-20 06:48:27.828000+03:00    22.187213
2015-08-20 06:48:29.720000+03:00    15.240609
2015-08-20 06:48:30.669000+03:00    24.781220
2015-08-20 06:48:33.793000+03:00    12.151207
2015-08-20 06:48:34.869000+03:00     9.230505
2015-08-20 06:48:37.708000+03:00     9.302840
dtype: float64

In [258]:
df['dist'] = dist
df['dt'] = dt

In [259]:
df1m = df.resample('1min').sum()

In [260]:
df1m.index

DatetimeIndex(['2015-08-20 06:48:00+03:00', '2015-08-20 06:49:00+03:00',
               '2015-08-20 06:50:00+03:00', '2015-08-20 06:51:00+03:00',
               '2015-08-20 06:52:00+03:00', '2015-08-20 06:53:00+03:00',
               '2015-08-20 06:54:00+03:00', '2015-08-20 06:55:00+03:00',
               '2015-08-20 06:56:00+03:00', '2015-08-20 06:57:00+03:00',
               '2015-08-20 06:58:00+03:00', '2015-08-20 06:59:00+03:00',
               '2015-08-20 07:00:00+03:00', '2015-08-20 07:01:00+03:00',
               '2015-08-20 07:02:00+03:00', '2015-08-20 07:03:00+03:00',
               '2015-08-20 07:04:00+03:00', '2015-08-20 07:05:00+03:00',
               '2015-08-20 07:06:00+03:00', '2015-08-20 07:07:00+03:00',
               '2015-08-20 07:08:00+03:00', '2015-08-20 07:09:00+03:00',
               '2015-08-20 07:10:00+03:00', '2015-08-20 07:11:00+03:00',
               '2015-08-20 07:12:00+03:00', '2015-08-20 07:13:00+03:00',
               '2015-08-20 07:14:00+03:00', '2015-0

In [261]:
df1m.columns

Index(['lat', 'lng', 'height', 'dist'], dtype='object')

In [262]:
df['dt'] = dt / np.timedelta64(1, 'h')
df1m = df.resample('1min').sum()
speed1m = df1m['dist'] / df1m['dt']

In [263]:
speed1m[:10]

time
2015-08-20 06:48:00+03:00     8.127204
2015-08-20 06:49:00+03:00     7.579874
2015-08-20 06:50:00+03:00     9.127708
2015-08-20 06:51:00+03:00    10.220254
2015-08-20 06:52:00+03:00    10.114795
2015-08-20 06:53:00+03:00     9.687816
2015-08-20 06:54:00+03:00    10.856153
2015-08-20 06:55:00+03:00    10.891833
2015-08-20 06:56:00+03:00    10.270188
2015-08-20 06:57:00+03:00     6.629179
Freq: T, dtype: float64